tests = [
    {
        # Example from PDF file
        "title": "Aswar example",
        "frames": [1, 2, 3, 5, 6, 10, 11, 16],
        "expected": {
            "gaps": [[4, 4], [7, 9], [12, 15]],
            "longest_gap": [12, 15],
            "missing_count": 8,
        },
    },
    {
        "title": "Empty list of frames",
        "frames": [],
        "expected": {
            "gaps": [],
            "longest_gap": [],
            "missing_count": 0,
        },
    },
    {
        "title": "Single gap",
        "frames": [1, 2, 3, 5, 6, 7, 8, 9, 10],
        "expected": {
            "gaps": [[4, 4]],
            "longest_gap": [4, 4],
            "missing_count": 1,
        },
    },
    {
        "title": "Multiple gaps with longest in the middle",
        "frames": [1, 2, 5, 6, 11, 12, 13],
        "expected": {
            "gaps": [[3, 4], [7, 10]],
            "longest_gap": [7, 10],
            "missing_count": 6,
        },
    },
    {
        "title": "Full list with no gaps",
        "frames": [1, 2, 3, 4, 5, 6, 7],
        "expected": {
            "gaps": [],
            "longest_gap": [],
            "missing_count": 0,
        },
    },
    {
        "title": "Descending order frames",
        "frames": [10, 8, 6, 4, 2],
        "expected": {
            "gaps": [[1, 1], [3, 3], [5, 5], [7, 7], [9, 9]],
            "longest_gap": [1, 1],
            "missing_count": 5,
        },
    },
    {
        "title": "Single frame received",
        "frames": [5],
        "expected": {
            "gaps": [[1, 4]],
            "longest_gap": [1, 4],
            "missing_count": 4,
        },
    },
    {
        "title": "Missing frames from the beginning",
        "frames": [5, 6, 7, 8],
        "expected": {
            "gaps": [[1, 4]],
            "longest_gap": [1, 4],
            "missing_count": 4,
        },
    },
    {
        "title": "Missing frames at the end",
        "frames": [1, 2, 3, 4, 5],
        "expected": {
            "gaps": [],
            "longest_gap": [],
            "missing_count": 0,
        },
    },
    {
        "title": "Randomly shuffled list with multiple gaps",
        "frames": [11, 2, 1, 8, 10, 5, 4],
        "expected": {
            "gaps": [[3, 3], [6, 7], [9, 9]],
            "longest_gap": [6, 7],
            "missing_count": 4,
        },
    },
    {
        "title": "All frames are missing",
        "frames": [10],
        "expected": {
            "gaps": [[1, 9]],
            "longest_gap": [1, 9],
            "missing_count": 9,
        },
    },
    {
        "title": "Large list with sequential and random gaps",
        "frames": [
            1,
            2,
            3,
            5,
            6,
            8,
            9,
            10,
            11,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            25,
            26,
            27,
            30,
            31,
            32,
            33,
            34,
            35,
            36,
            37,
            38,
            39,
            41,
            42,
            43,
            44,
            45,
            46,
            47,
            48,
            50,
            51,
            55,
            56,
            57,
            58,
            60,
            61,
            62,
            63,
            64,
            65,
            70,
            71,
            72,
            73,
            74,
            75,
        ],
        "expected": {
            "gaps": [
                [4, 4],
                [7, 7],
                [12, 14],
                [23, 24],
                [28, 29],
                [40, 40],
                [49, 49],
                [52, 54],
                [59, 59],
                [66, 69],
            ],
            "longest_gap": [66, 69],
            "missing_count": 19,
        },
    },
    {
        "title": "Large unordered list with a big gap in the middle",
        "frames": [
            10,
            5,
            30,
            25,
            3,
            2,
            28,
            12,
            1,
            22,
            15,
            18,
            20,
            19,
            21,
            14,
            27,
            24,
            6,
            26,
            7,
            9,
            8,
            11,
            4,
            13,
            23,
            16,
            17,
            29,
            50,
            48,
            45,
            42,
            49,
            47,
            46,
            43,
            41,
            44,
        ],
        "expected": {
            "gaps": [[31, 40]],
            "longest_gap": [31, 40],
            "missing_count": 10,
        },
    },
]
